import{i as c,S as g}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const r of a.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&o(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=i(e);fetch(e.href,a)}})();const l={error:{position:"topRight",class:"error",color:"white",timeout:3e3}},n={loading:"Loading images, please wait...",no_data:"Sorry, there are no images matching your search query. Please try again!",request_error:"Error during requesting"},m={error_no_data:{message:n.no_data,...l.error},request_error:{message:n.request_error,...l.error}};function f(s){const t=document.createElement("div");return t.textContent=s,t.classList.add("loader"),t}function v(s){return s.reduce((t,i)=>(t+=p(i),t),"")}function p(s){const{webformatURL:t,largeImageURL:i,tags:o,likes:e,views:a,comments:r,downloads:u}=s;return`
    <div class="image">
      <a class="image-link" href="${i}">
        <div class="image-photo-wrap"><img class="image-photo" src="${t}" data-source="${i}" alt="${o}"/></div>
        <div class="image-data">
          <div class="image-data-item image-data-item-likes"><div class="image-data-item-label">Likes</div><div class="image-data-item-number">${e}</div></div>
          <div class="image-data-item image-data-item-views"><div class="image-data-item-label">Views</div><div class="image-data-item-number">${a}</div></div>
          <div class="image-data-item image-data-item-comments"><div class="image-data-item-label">Comments</div><div class="image-data-item-number">${r}</div></div>
          <div class="image-data-item image-data-item-downloads"><div class="image-data-item-label">Downloads</div><div class="image-data-item-number">${u}</div></div>
      </div>
      </a>
    </div>
  `}let d;function h(s,t={}){const i=new URLSearchParams({key:"43799735-9794f2fe47020c8ff64ba54b4",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),{loaderEl:o,imagesEl:e}=t,a=`https://pixabay.com/api/?${i}`;fetch(a).then(r=>{if(!r.ok)throw n.request_error;return r.json()}).then(r=>{if(r.total<1){c.error(m.error_no_data),o.remove();return}e.innerHTML=v(r.hits),o.remove(),d?d.refresh():d=new g("#images .image-link",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250})}).catch(r=>{console.log(r),c.error(m.request_error),o.remove()})}document.addEventListener("DOMContentLoaded",s=>{const t=document.querySelector("#search-form"),i=f(n.loading),o=document.querySelector("#images");t.addEventListener("submit",e=>{e.preventDefault();const a=t.querySelector('input[name="search"]').value;o.innerHTML="",t.after(i),h(a,{loaderEl:i,imagesEl:o}),t.reset()})});
//# sourceMappingURL=commonHelpers.js.map
